# services:
#   # postgres:
#   #   image: postgres:17.5-alpine
#   #   restart: unless-stopped
#   #   ports:
#   #     - '5432:5432'
#   #   environment:
#   #     - POSTGRES_PASSWORD=password
#   #     - POSTGRES_USER=user
#   #     - POSTGRES_DB=crm_db
      
  
#   pgadmin:
#     image: dpage/pgadmin4
#     restart: unless-stopped
#     ports:
#       - "8080:80"
#     environment:
#       - PGADMIN_DEFAULT_EMAIL=admin@admin.com
#       - PGADMIN_DEFAULT_PASSWORD=admin
      


version: "3.9"

services:
  postgres:
    image: postgres:17.5-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crm_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: